Adding main structure to the top-level FAQ section.
casper-network/docs-app pull request #35
Opened 2021-10-18 09:42 UTC by Buddhika-Pathirathna

Create new files for each faq categories.
Remove faq-developers from Developers section and move to main FAQ.

### Related links

// Paste links to Github tasks or links to related PRs.

### Changes

// Paste brief description what has changed.

// Paste [loom](https://www.loom.com/), screenshots, or gifs([record](https://giphy.com/apps/giphycapture), [compress](https://gifcompressor.com/)) here.

### Notes

// Paste any other notes if any

2021-10-21 06:07 UTC, Buddhika-Pathirathna commented
> @Buddhika-Pathirathna I have added @GloreenS for review as well. Please let us know when you need the review since I see that the PR is still work in progress. If I am still OOO and you need to merge, please remove me as a reviewer. You can click "Ready for review", ping us here, or on the team channel. Thank you!

@ipopescu , Thanks for adding her too. I kept it draft since there are some content that still needs to be added. But, it seems I can add those separately and put this part to review. it is helpful if you both can review how the pages are structured for all 4 FAQ sections under the main FAQ page (top-level). main changes are,
- I have added four new sections under the main FAQ page
- Removed 'Getting help' section from 'Developers' and moved it under main 'FAQ' as 'FAQ - Developers'
- Removed content under the main FAQ and added it as 'FAQ-Enterprise' as a separate sectioon under main FAQ page

2021-10-28 12:44 UTC, GloreenS requested changes
Links to none of the categories are working, please check them. 
**Example**
*[Developers] (../docs/faq/faq-developer)* this link should be *[Developers] (faq-developer)* since the files are in the same folder.

Few points to consider:
- As a user with the current design, I am expected to know which type of user I am before I can search for a question.
- The left navigation should display the categories and maybe the questions within them if possible
- Is there a way to add a search element that can search through all the FAQ links at once?

2021-11-09 10:31 UTC, ipopescu requested changes
@Buddhika-Pathirathna, thank you! I am submitting suggestions for all files except faq-developer.md. The developers' content requires more work and formatting, so I will help with that in a separate commit.

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/index.md
> +title: FAQ Categories
I would change this back to the original title because the "FAQ Categories" title repeats below. You could use the original title or maybe use a new one: "Getting Help".

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/index.md
>  ---
I suggest updating the text on lines 6, 7 with: "This page consolidates several frequently-asked questions (FAQ) and organizes them into specific categories with links to access the full content of those FAQ sections."

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/index.md
> +| [General](/faq/faq-general)      | Contains details for all types of users covering general functionalities and domain details                           |
Suggestion: "Contains details for all types of users, covering general functionality and domain details"

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/index.md
> +| [Enterprise](/faq/faq-enterpise) | Specially for the business related details related to the Casper network, CasperLabs, and the CSPR token sale.        |
I would update the description to say "Business-related questions regarding the Casper Network, CasperLabs, and the CSPR token sale."

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/index.md
> +| [Developers](/faq/faq-developer) | Details related to the software development environment, related tools, setup issues, smart contracts problems etc... |
Suggested description: "Details related to the software development environment, developer tools, setup issues, smart contracts problems, and more"

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/index.md
> +| [Validators](/faq/faq-validator) | Details related to the validator functionalities                                                                      |
Suggestion: "Tips and details for network node operators (validators)"

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/faq-enterpise.md
Please update line 3 to say: "Frequently asked questions regarding the Casper Network, CasperLabs, and the CSPR token sale."

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/faq-enterpise.md
> + <summary><b><h3>What is Casper?</h3></b></summary>
Suggestion to remove h3, for all questions, to match the developers' section.

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/getting-started.md
> +For any incoming questions and issues refer our in-built [FAQ guide](/docs/faq/faq-developer) with questions and answers.
"Refer to our [FAQ guide](/docs/faq/faq-developer) if you have questions or need help."

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/faq-general.md
> +# FAQ - General
If the section is empty, say something like "Coming soon".

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/faq-validator.md
> +# FAQ - Validators
If the section is empty, say something like "Coming soon".

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/faq-developer.md
> +This section covers frequently asked questions and our recommendations from the developer's perspective.
Suggestion: "frequently-asked questions"

2021-11-09 10:31 UTC, ipopescu commented on source/docs/casper/faq/faq-developer.md
> +</details>
Please remove this one, it is internal to our CL developers. In the future, hopefully we will add a WSL2 section.

2021-11-09 13:32 UTC, ipopescu commented on source/docs/casper/faq/faq-developer.md
> +**Question** : This is specifically found when running an AWS image on the Windows machine. The command performed is 'cargo build --release',
@Buddhika-Pathirathna  I don't think this error is specific to running the AWS Ubuntu image on Windows. From what I understand, you are connecting remotely to the AWS Ubuntu image, from Windows. It should not matter that you are connecting from a Windows machine or not. I recommend removing this detail, as it may be confusing to those running into this issue directly on a Ubuntu machine.

2021-11-11 14:44 UTC, ipopescu approved these changes
Looks great, @Buddhika-Pathirathna! Thank you!

2021-11-11 14:45 UTC, ipopescu commented
@GloreenS when you get a chance, please take a look as well. Thanks!

2021-11-12 09:42 UTC, GloreenS approved these changes
Few minor changes identified within the files. Everything else looks good! The PR is approved.

2021-11-12 09:42 UTC, GloreenS commented on source/docs/casper/faq/faq-enterpise.md
> +# Casper Network
Change format to heading level2 for this and all the sectional headings in the FAQ - Enterprise.

2021-11-12 09:42 UTC, GloreenS commented on source/docs/casper/faq/faq-enterpise.md
> +
Capitalize Casper network to Casper Network. There are around 27 instances of this in the FAQ, please change it for all. As mentioned by Iulia in another review, this is going to be the standard for Casper Network usage henceforth.

2021-11-12 09:42 UTC, GloreenS commented on source/docs/casper/faq/faq-enterpise.md
> +
Add the abbreviation in brackets for Proof-of-Work (POW).

2021-11-12 09:42 UTC, GloreenS commented on source/docs/casper/faq/faq-enterpise.md
> +
Add abbreviation after the expanded form in brackets for Byzantine Fault Tolerant (BFT).

2021-11-12 10:47 UTC, merged